FROM node:18 AS builder

WORKDIR /app

COPY . .

COPY package*.json .

RUN npm install

RUN npm run build

FROM nginx:latest

COPY --from=builder /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 90

CMD ["nginx", "-g", "daemon off;"]
