version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "23301:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres?schema=public
      JWT_SECRET: 78b37db2f09767c7ad3eb47c903739359c69aa57080c2710db92fcb1809f8cd4
      JWT_TOKEN_AUDIENCE: "192.168.31.15:23302"
      JWT_TOKEN_ISSUER: "192.168.31.15:23302"
      JWT_ACCESS_TOKEN_TTL: 86400
    ports:
      - "23302:3000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "23303:90"
    depends_on:
      - backend

volumes:
  postgres_data:
  minio_data:
