version: "3"

services:
  minio:
    image: minio/minio
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "22811:9000"
      - "22812:22812"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":22812"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "22813:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    ports:
      - "22814:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres?schema=public
      JWT_SECRET: 78b37db2f09767c7ad3eb47c903739359c69aa57080c2710db92fcb1809f8cd4
      JWT_TOKEN_AUDIENCE: "192.168.100.27:22815"
      JWT_TOKEN_ISSUER: "192.168.100.27:22815"
      JWT_ACCESS_TOKEN_TTL: 86400
      MINIO_ENDPOINT: http://minio:9000
      MINIO_BUCKET: threed-control-system
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "22815:3000"
    depends_on:
      - db
      - redis
      - minio

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "22816:90"
    depends_on:
      - backend

volumes:
  postgres_data:
  minio_data:
