services:
  mahjong:
    container_name: mahjong
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "24301:3000"
    restart: always
    environment:
      JWT_SECRET: ""
      JWT_ACCESS_TOKEN_TTL: ""
      DATABASE_URL: ""
