export enum Permission {
  NONE = "NONE",
  FILE_UPLOAD = "FILE_UPLOAD",
  FILE_DOWNLOAD = "FILE_DOWNLOAD",
  LARGEFILE_UPLOAD = "LARGEFILE_UPLOAD",
  LARGEFILE_DOWNLOAD = "LARGEFILE_DOWNLOAD",
  CREATE_ROLE = "CREATE_ROLE",
  DELETE_ROLE = "DELETE_ROLE",
  UPDATE_ROLE = "UPDATE_ROLE",
  QUERY_ROLE = "QUERY_ROLE",
}
